exclude_paths:
- "utils/*"
engines:
  rubocop:
    enabled: true
    checks:
      Rubocop/Style/ClassAndModuleChildren:
        EnforcedStyle: compact
  duplication:
    enabled: true
    config:
      languages:
      - ruby
  fixme:
    enabled: true
  shellcheck:
    enabled: true
ratings:
  paths:
  - lib/**
  - actions/**
  - bin/miga
  - scripts/**
