version: "2"
plugins:
  rubocop:
    enabled: true
    checks:
      Rubocop/Style/AndOr:
        EnforcedStyle: conditionals
  fixme:
    enabled: true
  shellcheck:
    enabled: true
exclude_patterns:
- "utils/*"
