exclude_paths:
- "utils/*"
engines:
  rubocop:
    enabled: true
    exclude_fingerprints:
    # MiGA::GUI Class length
    - 84cace45d08652c53af0156cdfbe7d7d
  duplication:
    enabled: true
    config:
      languages:
      - ruby
  fixme:
    enabled: true
  shellcheck:
    enabled: true
ratings:
  paths:
  - lib/**
  - actions/**
  - bin/miga
  - gui/miga
  - scripts/**
