language: ruby
os: linux
before_install:
  - gem install bundler -v 1.17.3
jobs:
  include:
    # Run remote tests in only one version
    - rvm: 2.1.5
      env: REMOTE_TESTS=true
      after_script: "bundle exec codeclimate-test-reporter"
    # Additional tests with standard versions
    - rvm: 2.3.0
    - rvm: 2.5.1
    - rvm: ruby-head
script: "bundle exec rake test:all"
cache: bundler
addons:
  code_climate:
    repo_token: ae74feb57032eaec34d8b695e504f00fe300d01a2ec0055e41f107a20f512645
