language: ruby
rvm:
  - 1.9.3
  - 2.3.0
matrix:
  include:
    # Run remote tests in only one version
    - rvm: 2.1.5
      env: REMOTE_TESTS=true
    # Test GUI with JRuby
    - rvm: jruby-9.0.5.0
      gemfile: gui/Gemfile
      env: GUI_TESTS=true
      jdk: openjdk7
      before_script:
      - "export DISPLAY=:99.0"
      - "export SWT_GTK3=0"
      - "sh -e /etc/init.d/xvfb start"
      - "sleep 3"
      after_script:
      - find -name '*.log' -exec cat {} \;
script: "bundle exec rake test"
cache: bundler
addons:
  code_climate:
    repo_token: ae74feb57032eaec34d8b695e504f00fe300d01a2ec0055e41f107a20f512645
