language: ruby
rvm:
  - 1.9.3
  - 2.3.0
  - ruby-head
matrix:
  include:
    - rvm: 2.1.5
      env: REMOTE_TESTS=true
    - rvm: jruby
      gemfile: gui/Gemfile
script: "bundle exec rake test"
cache: bundler
addons:
  code_climate:
    repo_token: ae74feb57032eaec34d8b695e504f00fe300d01a2ec0055e41f107a20f512645
