language: ruby
os: linux
before_install:
  - gem install bundler -v 2.1.4
jobs:
  include:
    # Run remote tests in only one version
    - rvm: 2.3.8
      env: REMOTE_TESTS=true
      after_script: "bundle exec codeclimate-test-reporter"
    # Additional tests with standard versions
    - rvm: 2.5.1
    - rvm: 2.6.5
    - rvm: ruby-head
script: "bundle exec rake test:all"
cache: bundler
addons:
  code_climate:
    repo_token:
      secure: "jOgrOQzPGXW/JmU5jzC+aI8W3/+gTGBvNUza6ML7kEzyQFRzely3K/kZPq2Xl/wY3IKSzvRskbDpwn/+dVuUEC3Qrz5y0FYaVy9SUxBBZzD2uQYKeE8tfryixl5I6cJnK3V67TuXn27U+WrDJ6sxWfrtPhHJvw/K9vGq+RbwtiCdMC5BUvJ1o8vLAaNVj9vzL76B7ngC+vEwioCLBDPn/p20GkqE31siRpksxi6JvmHTwWpzAjahVNQwFaugEPl4TGBpxoyAlGfLba3OOACTenf7fzwCuTGpzAIrFuFKoKCTVFVceoxgCpcnrldkFQbfBzJshvA7+nIuxbYqophDIWfbCKa+uciJzZ1hlyfZdwwPCwQgTieayI8rP/KAeYvNKj9vx8yHKM6OlEN26JbBMFqxhpnaaj0WHVI05aT36bdu7+CjCeTRk3mPJoLvoTxIBvCqfhyT1d/Iw59Z8CJ9xEEsevAzsKbxHIOnnE5D0jChZsKTMdPWyzdXHNA/knFbXSzggLpfLan10uym9KWWI2TAEH1BjJRaNC5HADZ5wkSlpuhnuFaYqhM9HfD0F/qzjbtaZHUNj0Fn515fgjWABgPTP3i02W7TBF6WHZ/wVBKm44rVJIpljRUt3qpefho+P5PmwihO3kPLqtBMmkgwyGuqQQr9Q2Li5kL74hbPYeI="
