language: ruby
matrix:
  include:
    # Run remote tests in only one version
    - rvm: 2.1.5
      env: REMOTE_TESTS=true
      after_script: "bundle exec codeclimate-test-reporter"
    # Test with JRuby (for the GUI)
    - rvm: jruby-9.0.5.0
      env: JRUBY_TESTS=true JRUBY_OPTS="-d"
      jdk: openjdk7
    # Additional tests with standard versions
    - rvm: 1.9.3
    - rvm: 2.3.0
script: "bundle exec rake test:all"
cache: bundler
addons:
  code_climate:
    repo_token: ae74feb57032eaec34d8b695e504f00fe300d01a2ec0055e41f107a20f512645
